import { Company } from './company.model';

export const data: Company[] = [
  {
    id: '1',
    label: 'Shopify',
    industry: 'ecommerce',
    city: 'Ottawa',
    employees: '8000+',
    revenue: '3B+',
    website: 'https://www.shopify.com/careers',
  },
  {
    id: '2',
    label: 'Klarna',
    industry: 'finance',
    city: 'Stockholm',
    employees: '5000+',
    revenue: '5B+',
    website: 'https://www.klarna.com/careers/',
  },
  {
    id: '3',
    label: 'Reddit',
    industry: 'social media',
    city: 'San Francisco',
    employees: '2000+',
    revenue: '500M+',
    website: 'https://www.redditinc.com/careers',
  },
  {
    id: '4',
    label: 'Nike',
    industry: 'fashion',
    city: 'Beaverton',
    employees: '75000+',
    revenue: '45B+',
    website: 'https://jobs.nike.com/',
  },
  {
    id: '5',
    label: 'Zapier',
    industry: 'fashion',
    city: 'Remote',
    employees: '500+',
    revenue: '100M+',
    website: 'https://zapier.com/jobs/',
  },
  {
    id: '6',
    label: 'Revolut',
    industry: 'finance',
    city: 'London',
    employees: '5000+',
    revenue: '800M+',
    website: 'https://www.revolut.com/careers/',
  },
  {
    id: '7',
    label: 'Forever 21',
    industry: 'fashion',
    city: 'Los Angeles',
    employees: '30000+',
    revenue: '4B+',
    website: '',
  },
  {
    id: '8',
    label: 'Red Bull',
    industry: 'entertainment',
    city: 'Fuschl am See',
    employees: '13000+',
    revenue: '7B+',
    website: 'https://jobs.redbull.com/global/en',
  },
  {
    id: '9',
    label: 'Calvin Klein',
    industry: 'fashion',
    city: 'New York city',
    employees: '10000+',
    revenue: '3B+',
    website: '',
  },
  {
    id: '10',
    label: 'Intercom',
    industry: 'tech',
    city: 'San Francisco',
    employees: '600+',
    revenue: '150M+',
    website: 'https://www.intercom.com/careers',
  },
  {
    id: '11',
    label: 'Apple',
    industry: 'tech',
    city: 'Cupertino',
    employees: '150000+',
    revenue: '350B+',
    website: 'https://jobs.apple.com',
  },
  {
    id: '12',
    label: 'Amazon',
    industry: 'retail',
    city: 'Seattle',
    employees: '1500000+',
    revenue: '450B+',
    website: 'https://www.amazon.jobs/',
  },
  {
    id: '13',
    label: 'Netflix',
    industry: 'entertainment',
    city: 'Los Gatos',
    employees: '10000+',
    revenue: '30B+',
    website: 'https://jobs.netflix.com/',
  },
  {
    id: '14',
    label: 'Meta',
    industry: 'tech',
    city: 'Menlo Park',
    employees: '70000+',
    revenue: '100B+',
    website: 'https://www.metacareers.com/',
  },
  {
    id: '15',
    label: 'Google',
    industry: 'tech',
    city: 'Mountain View',
    employees: '150000+',
    revenue: '250B+',
    website: 'https://careers.google.com/',
  },
  {
    id: '16',
    label: 'Tesla',
    industry: 'automotive',
    city: 'Austin',
    employees: '100000+',
    revenue: '80B+',
    website: 'https://www.tesla.com/careers',
  },
  {
    id: '17',
    label: 'Microsoft',
    industry: 'tech',
    city: 'Redmond',
    employees: '200000+',
    revenue: '200B+',
    website: 'https://careers.microsoft.com/',
  },
  {
    id: '18',
    label: 'Samsung',
    industry: 'electronics',
    city: 'Seoul',
    employees: '300000+',
    revenue: '200B+',
    website: 'https://www.samsung.com/us/explore/careers/',
  },
  {
    id: '19',
    label: 'H&M',
    industry: 'fashion',
    city: 'Stockholm',
    employees: '100000+',
    revenue: '20B+',
    website: 'https://career.hm.com/content/hmcareer/',
  },
  {
    id: '20',
    label: 'Uber',
    industry: 'transportation',
    city: 'San Francisco',
    employees: '25000+',
    revenue: '20B+',
    website: 'https://www.uber.com/global/en/careers/list/',
  },
];
